[package]
name = "debridge-solana-sdk-example-client"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
debridge-invoke-example = { path = "../../programs/debridge-invoke-test", features = ["cpi", "no-entrypoint"] }
